# Generated by Django 5.2.3 on 2025-08-17 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        ('payouts', '0002_initial'),
        ('savings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutmodel',
            name='approved_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payoutmodel',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payoutmodel',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payoutmodel',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payoutmodel',
            name='cycle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='savings.savingscyclemodel'),
        ),
        migrations.AlterField(
            model_name='payoutmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='payoutmodel',
            constraint=models.UniqueConstraint(fields=('client', 'cycle'), name='one_payout_per_cycle'),
        ),
    ]
