# Generated by Django 5.2.3 on 2025-09-19 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_merge_20250918_1740'),
        ('payouts', '0003_payoutmodel_approved_on_payoutmodel_rejection_reason_and_more'),
        ('savings', '0002_savingscyclemodel_collector_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payoutmodel',
            name='one_payout_per_cycle',
        ),
        migrations.AddField(
            model_name='payoutmodel',
            name='payout_type',
            field=models.CharField(choices=[('client_specific', 'Client Specific'), ('bulk', 'Bulk Payout')], default='bulk', max_length=20),
        ),
        migrations.AlterField(
            model_name='payoutmodel',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clientmodel'),
        ),
        migrations.AlterField(
            model_name='payoutmodel',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='savings.savingscyclemodel'),
        ),
        migrations.AddConstraint(
            model_name='payoutmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('payout_type', 'client_specific')), fields=('client', 'cycle'), name='one_payout_per_client_cycle'),
        ),
    ]
