# Generated by Django 5.2.6 on 2025-10-12 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0002_update_payout_model'),
        ('payouts', '0004_remove_payoutmodel_one_payout_per_cycle_and_more'),
    ]

    operations = [
    ]
