# Generated by Django 5.2.6 on 2025-10-12 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0005_merge_20251012_0134'),
        ('savings', '0002_savingscyclemodel_collector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutmodel',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='savings.savingscyclemodel'),
        ),
    ]
