import { Client } from "./types";

// Mock Data
// export const mockClients: Client[] = [
//   {
//     id: '1',
//     name: 'Mary Asante',
//     phone_number: '+233 24 123 4567',
//     address: 'Tema Community 1',
//     savingsGoal: 5000,
//     dailyAmount: 50,
//     cycleDays: 30,
//     currentBalance: 1500,
//     daysCompleted: 30,
//     lastContribution: new Date(),
//     status: 'active',
//     assignedWorker: 'worker1',
//     createdAt: new Date(),
//     updatedAt: new Date(),
//   },
//   {
//     id: '2',
//     name: 'Kwame Osei',
//     phone: '+233 20 987 6543',
//     address: 'Ashaiman Market',
//     savingsGoal: 3000,
//     dailyAmount: 30,
//     cycleDays: 30,
//     currentBalance: 900,
//     daysCompleted: 30,
//     lastContribution: new Date(Date.now() - 86400000), // Yesterday
//     status: 'pending',
//     assignedWorker: 'worker1',
//     createdAt: new Date(),
//     updatedAt: new Date(),
//   },
//   {
//     id: '3',
//     name: 'Ama Boateng',
//     phone: '+233 26 555 7890',
//     address: 'Spintex Road',
//     savingsGoal: 8000,
//     dailyAmount: 80,
//     cycleDays: 30,
//     currentBalance: 2400,
//     daysCompleted: 30,
//     lastContribution: new Date(Date.now() - 172800000), // 2 days ago
//     status: 'active',
//     assignedWorker: 'worker1',
//     createdAt: new Date(),
//     updatedAt: new Date(),
//   },
//   {
//     id: '4',
//     name: 'Joseph Mensah',
//     phone: '+233 23 111 2222',
//     address: 'Nungua Estate',
//     savingsGoal: 10000,
//     dailyAmount: 100,
//     cycleDays: 30,
//     currentBalance: 10000,
//     daysCompleted: 100,
//     lastContribution: new Date(),
//     status: 'complete',
//     assignedWorker: 'worker1',
//     createdAt: new Date(),
//     updatedAt: new Date(),
//   },
//   {
//     id: '5',
//     name: 'Maryn Asante',
//     phone: '+233 24 123 4567',
//     address: 'Tema Community 1',
//     savingsGoal: 5000,
//     dailyAmount: 50,
//     cycleDays: 30,
//     currentBalance: 1500,
//     daysCompleted: 30,
//     lastContribution: new Date(),
//     status: 'active',
//     assignedWorker: 'worker1',
//     createdAt: new Date(),
//     updatedAt: new Date(),
//   },
//   {
//     id: '6',
//     name: 'Kwami',
//     phone: '+233 20 987 6543',
//     address: 'Ashaiman Market',
//     savingsGoal: 3000,
//     dailyAmount: 30,
//     cycleDays: 30,
//     currentBalance: 900,
//     daysCompleted: 30,
//     lastContribution: new Date(Date.now() - 86400000), // Yesterday
//     status: 'pending',
//     assignedWorker: 'worker1',
//     createdAt: new Date(),
//     updatedAt: new Date(),
//   },
//   {
//     id: '3',
//     name: 'Ama Boateng',
//     phone: '+233 26 555 7890',
//     address: 'Spintex Road',
//     savingsGoal: 8000,
//     dailyAmount: 80,
//     cycleDays: 30,
//     currentBalance: 2400,
//     daysCompleted: 30,
//     lastContribution: new Date(Date.now() - 172800000), // 2 days ago
//     status: 'active',
//     assignedWorker: 'worker1',
//     createdAt: new Date(),
//     updatedAt: new Date(),
//   },
//   {
//     id: '4',
//     name: 'Joseph Mensah',
//     phone: '+233 23 111 2222',
//     address: 'Nungua Estate',
//     savingsGoal: 10000,
//     dailyAmount: 100,
//     cycleDays: 30,
//     currentBalance: 10000,
//     daysCompleted: 100,
//     lastContribution: new Date(),
//     status: 'complete',
//     assignedWorker: 'worker1',
//     createdAt: new Date(),
//     updatedAt: new Date(),
//   },
// ];
