# Generated by Django 5.2.3 on 2025-08-17 05:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        ('contributions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributionmodel',
            old_name='cycle',
            new_name='savings_cycle',
        ),
        migrations.RemoveField(
            model_name='contributionmodel',
            name='collected_on',
        ),
        migrations.RemoveField(
            model_name='contributionmodel',
            name='paid_for_date',
        ),
        migrations.AddField(
            model_name='contributionmodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contributionmodel',
            name='days_covered',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contributionmodel',
            name='is_bulk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contributionmodel',
            name='is_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contributionmodel',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contributionmodel',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='clients.clientmodel'),
        ),
        migrations.AlterField(
            model_name='contributionmodel',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
