# Generated by Django 5.2.3 on 2025-09-18 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_collector_delete_behavior'),
        ('clients', '0002_initial'),
    ]

    operations = [
    ]
