# Generated by Django 5.2.6 on 2025-10-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_merge_20250918_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Initial balance when client is created', max_digits=10),
        ),
    ]
