# Generated by Django 5.2.6 on 2025-12-18 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clientmodel_initial_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='clientmodel',
            index=models.Index(fields=['name'], name='clients_cli_name_15caa4_idx'),
        ),
        migrations.AddIndex(
            model_name='clientmodel',
            index=models.Index(fields=['phone_number'], name='clients_cli_phone_n_18a101_idx'),
        ),
        migrations.AddIndex(
            model_name='clientmodel',
            index=models.Index(fields=['unique_code'], name='clients_cli_unique__a2fd24_idx'),
        ),
        migrations.AddIndex(
            model_name='clientmodel',
            index=models.Index(fields=['collector'], name='clients_cli_collect_36170f_idx'),
        ),
        migrations.AddIndex(
            model_name='clientmodel',
            index=models.Index(fields=['is_fixed'], name='clients_cli_is_fixe_2ae16d_idx'),
        ),
        migrations.AddIndex(
            model_name='clientmodel',
            index=models.Index(fields=['-created_at'], name='clients_cli_created_a4d8c9_idx'),
        ),
        migrations.AddIndex(
            model_name='clientmodel',
            index=models.Index(fields=['collector', '-created_at'], name='clients_cli_collect_c9c24c_idx'),
        ),
    ]
