# Generated by Django 5.2.3 on 2025-09-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_collector_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name of the worker/collector', max_length=100, null=True),
        ),
    ]
