# Generated by Django 5.2.3 on 2025-07-19 12:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsCycleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cycle_length', models.IntegerField(default=31)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('early_withdrawal', 'Early Withdrawal')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='clients.clientmodel')),
            ],
        ),
    ]
