# Generated by Django 5.2.3 on 2025-08-17 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        ('savings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savingscyclemodel',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_cycles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savingscyclemodel',
            name='commission_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savingscyclemodel',
            name='total_saved',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='savingscyclemodel',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_cycles', to='clients.clientmodel'),
        ),
        migrations.AlterField(
            model_name='savingscyclemodel',
            name='cycle_length',
            field=models.PositiveIntegerField(default=31, help_text='Number of days for this savings cycle'),
        ),
        migrations.AlterField(
            model_name='savingscyclemodel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savingscyclemodel',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='savingscyclemodel',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('paid_out', 'Paid Out')], default='active', max_length=20),
        ),
    ]
