# Generated by Django 5.2.6 on 2025-10-12 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clientmodel_initial_balance'),
        ('savings', '0002_savingscyclemodel_collector_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savingscyclemodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='savingscyclemodel',
            index=models.Index(fields=['client', 'status'], name='savings_sav_client__538ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='savingscyclemodel',
            index=models.Index(fields=['status', 'end_date'], name='savings_sav_status_081f74_idx'),
        ),
    ]
